Teiid-Designer/teiid-designer

- plugins/teiid/org.teiid.runtime.client/src/org/teiid/runtime/client/proc/ProcedureService.java
Added logic to account for JSON as well as XML. In the case of JSON there is no need to add the starting tic, since we will always have one by default.
> teiiddes-2410

- plugins/org.teiid.designer.modelgenerator.ldap.ui/src/org/teiid/designer/modelgenerator/ldap/ui/wizards/LdapImportWizardManager.java
- plugins/org.teiid.designer.modelgenerator.ldap.ui/src/org/teiid/designer/modelgenerator/ldap/ui/wizards/pages/columns/LdapColumnsPage.java
- plugins/org.teiid.designer.modelgenerator.ldap.ui/src/org/teiid/designer/modelgenerator/ldap/ui/wizards/pages/columns/LdapEntryLabelProvider.java
- plugins/org.teiid.designer.modelgenerator.ldap.ui/src/org/teiid/designer/modelgenerator/ldap/ui/wizards/pages/table/LdapConnectionLabelProvider.java
- plugins/org.teiid.designer.modelgenerator.ldap.ui/src/org/teiid/designer/modelgenerator/ldap/ui/wizards/pages/table/LdapTablesPage.java
* LdapImportWizardManager
* Stop setSynchronising from notifying that it has changed as this is
calling update in the middle of user-selection operations. Not least
it is simply a flag that is observed via isSynchronising()
* Ldap[Columns|Tables]Page
* Refactor the tree viewers of these pages to be CheckboxTreeViewers as
this avoids the expensive method of WidgetUtil.findTreeItem().
* With the change to setSynchronising the performance of the trees is much
improved
> TEIIDDES-2299: Improve the performance of ldap wizard checkbox selection

- plugins/org.teiid.designer.webservice.ui/src/org/teiid/designer/webservice/ui/wizard/WsdlSelectionPage.java
Removed extraneous call to setParent of the web service model builder. This was overriding the project path which should always be the parent.
> teiiddes-2422: 

- plugins/org.teiid.designer.transformation.ui/src/org/teiid/designer/transformation/ui/reconciler/datatype/DatatypeReconcilerPanel.java
- corrects the viewer.refresh method calls.  It was supplying a 'true' arg, but that's not what is expected.  For full table refresh, now just using the no arg method to refresh the whole table.
> TEIIDDES-2418 Fixes DataType reconciler table update problem

- plugins/org.teiid.designer.dqp.ui/src/org/teiid/designer/runtime/ui/connection/CreateDataSourceAction.java
The original code was checking whether the selected source model has a
connection profile set, and would show an error message when it doesn't.
This was failing in case the CreateDataSourceAction was called from the
servers view. Added a null check to prevent the error in this case.
> TEIIDDES-2540 Add null check for model

- plugins/org.teiid.designer.datatools.ui/src/org/teiid/designer/datatools/profiles/ws/ParameterPanel.java
- plugins/org.teiid.designer.datatools.ui/src/org/teiid/designer/datatools/profiles/ws/PropertyPage.java
- plugins/org.teiid.designer.datatools.ui/src/org/teiid/designer/datatools/profiles/ws/WSProfileDetailsWizardPage.java
The key value was not always unique since we were not consistently using "rest_param:" when adding entries to the map which created apparent duplicate entries. Changed logic to consistently prefix the map key value with "rest_param:".
> teiiddes-2542

- plugins/org.teiid.designer.ui/src/org/teiid/designer/ui/refactor/RefactorResourcesUtils.java
- RefactorResourcesUtils was determining the OS, then handling the refactor differently to account for different line terminators on Windows OS.  Instead, we need to peek at the file to determine the line separator - because (for example) the model file may have been created on linux then moved to Windows.  In that case it would still have linux line separators.  Added a method to look at the file and determine the type of line separator.
> TEIIDDES-2551 Resolves renaming issue on Windows OS

- plugins/org.teiid.designer.datatools.ui/src/org/teiid/designer/datatools/profiles/ws/WSSoapPropertyPage.java
- plugins/org.teiid.designer.modelgenerator.wsdl.ui/src/org/teiid/designer/modelgenerator/wsdl/ui/wizards/soap/WsdlDefinitionPage.java
Nulled out validation message after display to prevent it from popping up when selecting "Back" in the wizard. Fixed check for changed CP since it was comparing the same instance to itself. Saved off CP properties prior to editing and compare those with current CP property values after editing. This will force an edited CP to get reloaded after edit, which was not happening before. Also fixed missing message key for endpoint tooltip.
> teiiddes-2526

- plugins/org.teiid.designer.datatools.ui/src/org/teiid/designer/datatools/profiles/ws/WSSoapPropertyPage.java
- plugins/org.teiid.designer.modelgenerator.wsdl.ui/src/org/teiid/designer/modelgenerator/wsdl/ui/wizards/soap/WsdlDefinitionPage.java
Nulled out validation message after display to prevent it from popping up when selecting "Back" in the wizard. Fixed check for changed CP since it was comparing the same instance to itself. Saved off CP properties prior to editing and compare those with current CP property values after editing. This will force an edited CP to get reloaded after edit, which was not happening before. Also fixed missing message key for endpoint tooltip.
> teiiddes-2526-9.0.x

- plugins/org.teiid.designer.modelgenerator.salesforce/src/org/teiid/designer/modelgenerator/salesforce/util/SalesForceConnectionInfoProvider.java
- the provider now checks for either a lowercase or uppercase 'url' property key.  The designer created connection profiles use the lowercase convention.  Teiid SF datasource use the uppercase convention, so the URL property key that is injected into a ModelResource is uppercase.  The infoProvider now handles either situation.
> TEIIDDES-2579 Ensure custom salesforce url is pushed to preview adapter

- plugins/org.teiid.designer.ui/src/org/teiid/designer/ui/refactor/move/MoveResourcesRefactoring.java
- model imports were not being resolved following model move into or out of a folder.
- added import element change calculation, as done in other methods.
> TEIIDDES-2604 Fixes Model Move Refactoring issue with imports

- plugins/teiid/org.teiid.runtime.client/api/org/teiid/translator/CacheDirective.java
- plugins/teiid/org.teiid.runtime.client/engine/org/teiid/query/parser/AbstractTeiidParser.java
- plugins/teiid/org.teiid.runtime.client/engine/org/teiid/query/parser/QueryParser.java
- plugins/teiid/org.teiid.runtime.client/engine/org/teiid/query/sql/lang/CacheHint.java
- plugins/teiid/org.teiid.runtime.client/engine/org/teiid/query/sql/visitor/SQLStringVisitor.java
* SQLStringVisitor
* cache hint addition being missed while visiting CreateProcedureCommand
* CacheDirective
* CacheHint
* adds parser as field to allow toString() method to work correctly
* implements toString method
* QueryParser
* Reduces number of TeiidParser instances being created
> TEIIDDES-2562: cache hint being lost from Create Procedure Command

- plugins/org.teiid.designer.core/src/org/teiid/designer/core/i18n.properties
- plugins/org.teiid.designer.core/src/org/teiid/designer/core/validation/ValidationRuleManager.java
- plugins/org.teiid.designer.core/src/org/teiid/designer/core/validation/rules/CircularDependenciesRule.java
- plugins/org.teiid.designer.core/src/org/teiid/designer/core/workspace/WorkspaceResourceFinderUtil.java
- plugins/org.teiid.designer.mapping.ui/src/org/teiid/designer/mapping/ui/editor/MappingDiagramController.java
- plugins/org.teiid.designer.ui/launch/Designer MacOSX.launch
- plugins/org.teiid.designer.ui/src/org/teiid/designer/ui/explorer/ModelExplorerResourceNavigator.java
- tests/org.teiid.core.designer.test.framework/src/org/teiid/core/designer/EclipseMock.java
- tests/org.teiid.designer.core.test/src/org/teiid/designer/core/test/AllTests.java
- tests/org.teiid.designer.core.test/src/org/teiid/designer/core/workspace/WorkspaceResourceFinderUtilTest.java
TEIIDDES-2620 Add validation rule to check for circular dependencies in view models
TEIIDDES-2611 Resize transformation editor crash Developer Studio
- added validation rule to detect circular dependencies
- fixed WorkspaceResourceFinderUtil.getResourcesThatUse so that it can handle circular dependencies
- created WorkspaceResourceFinderUtilTest to test the new circular dependency method
- Removed MappingDiagramController control listener that was causing display issues when the splitter was moved in the mapping editor
> Fix For TEIIDDES-2620 and TEIIDDES-2611

- plugins/org.teiid.designer.ui/src/org/teiid/designer/ui/explorer/ModelExplorerResourceNavigator.java
- commit of blafond fix for ModelExplorer selection problem.  ModelExplorer tree selections were not firing selection events - hence the properties panel was not updating on selection, etc.
> Fix ModelExplorer selection issue

- plugins/org.teiid.designer.modelgenerator.wsdl.ui/src/org/teiid/designer/modelgenerator/wsdl/ui/wizards/soap/WsdlDefinitionPage.java
Modified check for previous and current connection profile to check for one null and one non-null when comparing for updating the page. This will cause the WSDL URI to be set and allow the page to load properly.
> teiiddes-2656

- plugins/org.teiid.designer.modelgenerator.wsdl.ui/src/org/teiid/designer/modelgenerator/wsdl/ui/wizards/soap/WsdlDefinitionPage.java
Modified check for previous and current connection profile to check for one null and one non-null when comparing for updating the page. This will cause the WSDL URI to be set and allow the page to load properly.
> teiiddes-2656-9.0.x

- features/org.teiid.designer.crypto.dummy.feature/.project
- features/org.teiid.designer.crypto.dummy.feature/AUTHORS.txt
- features/org.teiid.designer.crypto.dummy.feature/LEGAL.txt
- features/org.teiid.designer.crypto.dummy.feature/build.properties
- features/org.teiid.designer.crypto.dummy.feature/feature.properties
- features/org.teiid.designer.crypto.dummy.feature/feature.xml
- features/org.teiid.designer.crypto.dummy.feature/license.html
- features/org.teiid.designer.crypto.dummy.feature/pom.xml
- features/org.teiid.designer.feature/feature.xml
- features/pom.xml
- plugins/crypto/org.teiid.designer.bc.dummy/.classpath
- plugins/crypto/org.teiid.designer.bc.dummy/.project
- plugins/crypto/org.teiid.designer.bc.dummy/COPYRIGHT.txt
- plugins/crypto/org.teiid.designer.bc.dummy/LICENSE-lgpl-2.1.txt
- plugins/crypto/org.teiid.designer.bc.dummy/META-INF/MANIFEST.MF
- plugins/crypto/org.teiid.designer.bc.dummy/build.properties
- plugins/crypto/org.teiid.designer.bc.dummy/plugin.properties
- plugins/crypto/org.teiid.designer.bc.dummy/pom.xml
- plugins/crypto/org.teiid.designer.bc.dummy/src/org/bouncycastle/asn1/ASN1Object.java
- plugins/crypto/org.teiid.designer.bc.dummy/src/org/bouncycastle/x509/extension/X509ExtensionUtil.java
- plugins/crypto/pom.xml
- plugins/pom.xml
* Due to the questioning legality of distributing Bouncy Castle, this
works around the dependency by providing dummy versions of the required
classes, which do very little.
* Limitation being that there is no support for X.509 attributes in
LDAP servers.
> TEIIDDES-2667: Provides a dummy plugin to avoid use of Bouncy Castle

- plugins/org.teiid.designer.transformation.ui/src/org/teiid/designer/transformation/ui/wizards/file/TeiidMetadataImportSourcePage.java
Project was null on the fileinfo object. Set project after browsing to a source folder and removed extraneous check for the project since we are already checking for the source model folder.
> teiiddes-2679:

- plugins/org.teiid.designer.transformation.ui/src/org/teiid/designer/transformation/ui/wizards/file/TeiidMetadataImportSourcePage.java
Project was null on the fileinfo object. Set project after browsing to a source folder and removed extraneous check for the project since we are already checking for the source model folder.
> teiiddes-2679

- plugins/org.teiid.designer.jdbc.relational/src/org/teiid/designer/jdbc/relational/i18n.properties
- plugins/org.teiid.designer.jdbc.relational/src/org/teiid/designer/jdbc/relational/impl/custom/SybaseModelProcessor.java
Attempt to set the correct name in source for tables imported from
Sybase. Sybase does not return a list of schemas, but still requires the
fully qualified name to include the owner.
We workaround this by obtaining the metadata for each imported table and
getting the "schema" from there.
In case of any problem, we fall back on the original behaviour.
> TEIIDDES-2458 Fix name in source for Sybase

- plugins/org.teiid.designer.ui/src/org/teiid/designer/ui/refactor/delete/DeleteResourcesRefactoring.java
The scenario in the jira has 4 duplicate warning messages about a readonly file during project deletion.
- The checkModelResourceWritable check at line 186 is redundant.  There is a writable check on generic resource a few lines above it.
- The checkValidFile override was also resulting in an extra warning.
> TEIIDDES-2674 Fixes issue with multiple file readonly warnings on delete

- plugins/org.teiid.designer.query.ui/src/org/teiid/query/ui/sqleditor/component/DisplayNode.java
- plugins/org.teiid.designer.spi/src/org/teiid/designer/query/sql/ISQLStringVisitor.java
- plugins/teiid/org.teiid.runtime.client/engine/org/teiid/query/sql/visitor/SQLStringVisitor.java
- tests/org.teiid.designer.query.ui.test/src/org/teiid/query/ui/sqleditor/component/TestDisplayNodeWithComments.java
- tests/org.teiid.runtime.client.test/src/org/teiid/query/sql/AbstractTestQueryParser.java
* Let DisplayNode stop the SQLStringVisitor from outputting comments when
called by its LanguageObject child classes, eg. SelectDisplayNode
* Another swing at controlling tab generation prepended to comments
> Small fixes for SQL syntax comments

- plugins/org.teiid.designer.vdb/src/org/teiid/designer/vdb/XmiVdb.java
- tests/org.teiid.designer.vdb.test/src/org/teiid/designer/vdb/dynamic/TestDynamicVdbExport.java
* Rather than blindly copying all the model properties, exclude the
indexName and checksum properties since they are at best irrelevant and
at worst count-productive to the dynamic vdb.
> TEIIDDES-2831: Excludes model properties during dynamic vdb conversion

- plugins/org.teiid.designer.vdb/src/org/teiid/designer/vdb/VdbModelEntry.java
- plugins/org.teiid.designer.vdb/src/org/teiid/designer/vdb/XmiVdb.java
* Added NATIVE metadata tag for overriding translator which source translator is infinispan-hotrod
* Fix getTranslatorOverride() function on VdbModelEntry. Now, the function returns overriding translator only for the model (VdbModelEntry) where is used.
If one model contains overriding translator, getTranslatorOverride() method return this translator for all models from VDB which has set some translator.
> TEIIDDES 3142 - add native metadata tag for overriding translator

- plugins/org.teiid.designer.vdb.ui/src/org/teiid/designer/vdb/ui/editor/panels/PropertiesPanel.java
- plugins/org.teiid.designer.vdb/src/org/teiid/designer/vdb/BasicVdb.java
BY_VERSION connection type was set as default connection type (according to [Teiid documentation](https://teiid.gitbooks.io/documents/content/admin/VDB_Versioning.html)) when VDB doesn't contain any information about this type. Also, BY_VERSION shows in the UI as default.
> TEIIDDES-3087
