plugins/org.teiid.designer.datatools.ui/src/org/teiid/designer/datatools/profiles/ws/ParameterPanel.java, plugins/org.teiid.designer.datatools.ui/src/org/teiid/designer/datatools/profiles/ws/PropertyPage.java, plugins/org.teiid.designer.datatools.ui/src/org/teiid/designer/datatools/ui/i18n.properties, plugins/org.teiid.designer.transformation.ui/src/org/teiid/designer/transformation/ui/i18n.properties, plugins/org.teiid.designer.transformation.ui/src/org/teiid/designer/transformation/ui/wizards/rest/TeiidRestImportSourcePage.java
Fixes parameter deletion issue, parsing issue (caused by XML conversion from a JSON object without a root), and the duplicate row of parameters after editing the default value.
=> teiiddes-2415: 

plugins/org.teiid.designer.datatools.ui/src/org/teiid/designer/datatools/profiles/ws/ParameterPanel.java, plugins/org.teiid.designer.transformation.ui/src/org/teiid/designer/transformation/ui/wizards/rest/ModelsDefinitionSection.java, plugins/org.teiid.designer.transformation.ui/src/org/teiid/designer/transformation/ui/wizards/rest/TeiidRestImportSourcePage.java
Fix for new CP not updating page and fix for NPE causing the view name validation message to stick around.
=> teiiddes-2415 - 

plugins/org.teiid.designer.dqp.ui/src/org/teiid/designer/runtime/ui/wizards/webservices/util/RestWebArchiveBuilderImpl.java
Changed XML/CLOB/BLOB results to be returned as streams instead of strings.
=> teiiddes-2431

plugins/org.teiid.designer.datatools.ui/src/org/teiid/designer/datatools/profiles/ws/ParameterPanel.java, plugins/org.teiid.designer.transformation.ui/src/org/teiid/designer/transformation/ui/wizards/rest/TeiidRestImportSourcePage.java
Fix to update parameter values after editing in the parameter panel of the property editor, fix for parsing file name for URI without parameters, and fix for missing message key.
=> teiiddes-2415

plugins/org.teiid.designer.datatools.ui/src/org/teiid/designer/datatools/profiles/ws/ParameterPanel.java
Removed extraneous call to handleAddParameter()
=> teiiddes-2451

plugins/org.teiid.designer.transformation.ui/src/org/teiid/designer/transformation/ui/wizards/rest/TeiidRestImportSourcePage.java
=> teiiddes-2457

plugins/org.teiid.designer.transformation.ui/src/org/teiid/designer/transformation/ui/wizards/rest/TeiidRestImportSourcePage.java
Added dialog to display error when parsing of JSON document fails.
=> teiiddes-2439

plugins/org.teiid.designer.transformation.ui/src/org/teiid/designer/transformation/ui/wizards/rest/TeiidRestImportSourcePage.java
Port of teiiddes-2439 fix to master
=> teiiddes-2439-master

plugins/org.teiid.designer.transformation.ui/src/org/teiid/designer/transformation/ui/wizards/rest/TeiidRestImportSourcePage.java
Port of teiiddes-2457 to master.
=> teiiddes-2457-master

plugins/org.teiid.designer.spi/src/org/teiid/designer/runtime/version/spi/TeiidServerVersion.java, plugins/org.teiid.designer.teiidimporter.ui/src/org/teiid/designer/teiidimporter/ui/panels/DataSourceManager.java, plugins/org.teiid.designer.teiidimporter.ui/src/org/teiid/designer/teiidimporter/ui/panels/TranslatorHelper.java
- changed from Integer.compare to be compatible with java 1.6
=> Changes for backward compatibility with java 1.6

plugins/org.teiid.designer.webservice.ui/src/org/teiid/designer/webservice/ui/wizard/WsdlSelectionPage.java
Port teiiddes-2422 fix to master.
=> teiiddes-2422

plugins/org.teiid.designer.datatools/src/org/teiid/designer/datatools/profiles/ws/WSConnectionInfoProvider.java
=> teiiddes-2245-master

plugins/org.teiid.designer.datatools/src/org/teiid/designer/datatools/profiles/ws/WSConnectionInfoProvider.java, plugins/org.teiid.designer.diagram.ui/src/org/teiid/designer/diagram/ui/custom/actions/NewCustomDiagramSiblingAction.java, plugins/org.teiid.designer.modelgenerator.wsdl.ui/src/org/teiid/designer/modelgenerator/wsdl/ui/wizards/soap/panels/ImportOptionsPanel.java, plugins/org.teiid.designer.transformation.ui/src/org/teiid/designer/transformation/ui/wizards/xmlfile/TeiidXmlFileImportProcessor.java, plugins/teiid/org.teiid.runtime.client/engine/org/teiid/query/proc/wsdl/WsdlRequestProcedureHelper.java
Cleaned up if statement in WSConnectionInfoProvider as well as other places.
=> teiiddes-2477

plugins/org.teiid.designer.modelgenerator.wsdl.ui/src/org/teiid/designer/modelgenerator/wsdl/ui/Messages.java, plugins/org.teiid.designer.modelgenerator.wsdl.ui/src/org/teiid/designer/modelgenerator/wsdl/ui/messages.properties, plugins/org.teiid.designer.modelgenerator.wsdl.ui/src/org/teiid/designer/modelgenerator/wsdl/ui/wizards/soap/ColumnInfo.java, plugins/org.teiid.designer.modelgenerator.wsdl.ui/src/org/teiid/designer/modelgenerator/wsdl/ui/wizards/soap/EditColumnDialog.java, plugins/org.teiid.designer.modelgenerator.wsdl.ui/src/org/teiid/designer/modelgenerator/wsdl/ui/wizards/soap/OperationsDetailsPage.java, plugins/org.teiid.designer.modelgenerator.wsdl.ui/src/org/teiid/designer/modelgenerator/wsdl/ui/wizards/soap/panels/ColumnsInfoPanel.java, plugins/org.teiid.designer.modelgenerator.wsdl.ui/src/org/teiid/designer/modelgenerator/wsdl/ui/wizards/soap/panels/EditColumnsPanel.java
Changed the SOAP importer to use tree table columns instead of CellEditor since CellEditor causes Macs to hang.
=> teiiddes-2455

plugins/org.teiid.designer.ui/src/org/teiid/designer/ui/refactor/RefactorResourcesUtils.java
- comparison of the path with xmi content was failing, due to difference in path separator on windows.
=> TEIIDDES-2434 Resolves refactor - rename issue on Windows OS

plugins/teiid/org.teiid.runtime.client/src/org/teiid/runtime/client/messages.properties
Removed extraneous 'response' from SQL template.
=> teiiddes-2489

plugins/org.teiid.designer.ui/src/org/teiid/designer/ui/refactor/RefactorResourcesUtils.java
- RefactorResourcesUtils was determining the OS, then handling the refactor differently to account for different line terminators on Windows OS. Instead, we need to peek at the file to determine the line separator - because (for example) the model file may have been created on linux then moved to Windows. In that case it would still have linux line separators. Added a method to look at the file and determine the type of line separator.
=> TEIIDDES-2551 Resolves renaming issue on Windows OS

plugins/org.teiid.designer.webservice.ui/src/org/teiid/designer/webservice/ui/actions/GenerateRestVirtualProceduresAction.java
Changed the list of parameter to column mappings to be a LinkedList so that order is preserved.
=> teiiddes-2566: 

plugins/org.teiid.designer.dqp.ui/src/org/teiid/designer/runtime/ui/wizards/webservices/util/RestWebArchiveBuilderImpl.java, plugins/org.teiid.designer.webservice.lib/rest_war_resources/webapps/index.html
Removed hard-coded value for url and made it dynamic based on war context and model. Also removed alert dialog and regex check.
=> teiiddes-2595

plugins/org.teiid.designer.dqp.ui/src/org/teiid/designer/runtime/ui/wizards/webservices/util/RestWebArchiveBuilderImpl.java, plugins/org.teiid.designer.webservice.lib/rest_war_resources/webapps/index.html
Removed hard-coded value for url and made it dynamic based on war context and model. Also removed alert dialog and regex check.
=> teiiddes-2595: 

plugins/org.teiid.designer.dqp.ui/src/org/teiid/designer/runtime/ui/connection/CreateVdbDataSourceAction.java, plugins/org.teiid.designer.dqp.ui/src/org/teiid/designer/runtime/ui/connection/VdbDataSourceInfo.java, plugins/org.teiid.designer.dqp.ui/src/org/teiid/designer/runtime/ui/i18n.properties, plugins/org.teiid.designer.dqp/src/org/teiid/designer/runtime/TeiidServer.java
Corrected connection url for Create VDB Datasource and Deploy VDB in the REST action set. Also, removed "-ds.xml" verbiage from the Deploy VDB/Create Datasource dialog.
=> teiiddes-1816

plugins/org.teiid.designer.ddl.importer/src/org/teiid/designer/ddl/importer/node/TeiidDdlImporter.java
- changes TeiidDdlImporter to work around the extension property issue described in TEIID-3629.  If the salesforce extension property with incorrect case is encountered, it is changed to the correct camel case name.  This change will have no adverse affect on later teiid versions where the extension property is correct.
=> TEIIDDES-2631 Handles incorrect case on Salesforce extension property

plugins/org.teiid.designer.modelgenerator.salesforce/src/org/teiid/designer/modelgenerator/salesforce/RelationalModelgenerator.java
- removed 'salesforce' schema creation.  The tables and procs are now put directly under the model instead of a salesforce schema.
=> TEIIDDES-2490 Salesforce importer no longer creates salesforce schema

plugins/org.teiid.designer.transformation.ui/src/org/teiid/designer/transformation/ui/i18n.properties, plugins/org.teiid.designer.transformation.ui/src/org/teiid/designer/transformation/ui/wizards/rest/ModelsDefinitionSection.java
Corrected missing message key.
=> teiiddes-2632

plugins/org.teiid.designer.spi/src/org/teiid/designer/query/sql/ISQLConstants.java, plugins/teiid/org.teiid.runtime.client/engine/org/teiid/query/proc/wsdl/WsdlWrapperHelper.java
Changed generated invoke() to use named parameters.
=> teiiddes-2633

plugins/org.teiid.designer.ddl.importer/src/org/teiid/designer/ddl/importer/node/EmfModelGenerator.java, plugins/org.teiid.designer.ddl/src/org/teiid/designer/ddl/IntermediateFormat.java, plugins/org.teiid.designer.metamodels.xml/src/org/teiid/designer/metamodels/xml/XmlDocumentBuilderImpl.java, plugins/org.teiid.designer.relational/src/org/teiid/designer/relational/model/RelationalReferenceFactory.java, plugins/org.teiid.designer.transformation.ui/src/org/teiid/designer/transformation/ui/wizards/TransformationCopyModelFeaturePopulator.java, plugins/org.teiid.designer.transformation/src/org/teiid/designer/transformation/materialization/MaterializationModelGenerator.java, plugins/org.teiid.designer.ui/src/org/teiid/designer/ui/favorites/ModelerCacheEventManager.java, plugins/org.teiid.designer.ui/src/org/teiid/designer/ui/properties/PropertyEditorFactory.java, plugins/org.teiid.designer.ui/src/org/teiid/designer/ui/wizards/ConvertToEnterpriseTypesWizard.java, plugins/org.teiid.designer.ui/src/org/teiid/designer/ui/wizards/StructuralCopyModelFeaturePopulator.java, plugins/org.teiid.designer.xsd.ui/src/org/teiid/designer/xsd/ui/editor/FacetHelper.java, tests/org.teiid.designer.vdb.test/src/org/teiid/designer/komodo/vdb/TestModelToDdlGenerator.java
* The test was failing due to the EmfModelGenerator caching an old instance
of the ModelerCore.ModelEditor
* Avoids caching the ModelEditor and prefers to retrieve it from
ModelerCore
=> Fixes error failing test in TestModelToDdlGenerator

plugins/org.teiid.designer.modelgenerator.wsdl.ui/src/org/teiid/designer/modelgenerator/wsdl/ui/wizards/soap/ColumnInfo.java, plugins/org.teiid.designer.modelgenerator.wsdl.ui/src/org/teiid/designer/modelgenerator/wsdl/ui/wizards/soap/ProcedureInfo.java, plugins/org.teiid.designer.relational/src/org/teiid/designer/relational/model/RelationalColumn.java, plugins/org.teiid.designer.spi/src/org/teiid/designer/query/proc/wsdl/IWsdlColumnInfo.java, plugins/org.teiid.designer.transformation.ui/src/org/teiid/designer/transformation/ui/editors/EditColumnDialog.java, plugins/org.teiid.designer.transformation.ui/src/org/teiid/designer/transformation/ui/wizards/EditColumnDialog.java, plugins/org.teiid.designer.transformation.ui/src/org/teiid/designer/transformation/ui/wizards/rest/TeiidRestImportProcessor.java
Removed "integer" from the datatype drop-down for SOAP and REST column editors. Also added logic to convert SOAP elements of type "integer" to "biginteger" when a column is added in the wizard.
=> teiiddes-2554:

plugins/org.teiid.datatools.connectivity/src/org/teiid/datatools/connectivity/model/Parameter.java, plugins/org.teiid.designer.datatools.ui/src/org/teiid/designer/datatools/profiles/ws/HeaderPropertiesPanel.java, plugins/org.teiid.designer.datatools.ui/src/org/teiid/designer/datatools/profiles/ws/ParameterPanel.java, plugins/org.teiid.designer.datatools.ui/src/org/teiid/designer/datatools/profiles/ws/PropertyPage.java, plugins/org.teiid.designer.datatools.ui/src/org/teiid/designer/datatools/profiles/ws/WSProfileDetailsWizardPage.java, plugins/org.teiid.designer.datatools/src/org/teiid/designer/datatools/profiles/ws/WSConnectionInfoProvider.java, plugins/org.teiid.designer.relational.ui/src/org/teiid/designer/relational/ui/webservice/WebServiceRelationalModelContributor.java, plugins/org.teiid.designer.transformation.ui/src/org/teiid/designer/transformation/ui/wizards/rest/TeiidRestImportSourcePage.java, plugins/org.teiid.designer.transformation.ui/src/org/teiid/designer/transformation/ui/wizards/xmlfile/XmlFileViewModelFactory.java, plugins/teiid/org.teiid.runtime.client/src/org/teiid/runtime/client/proc/ProcedureService.java
Added "headers" parameter to invokeHttp() generated procedure for REST web service imports. The header parameters added to the connection profile will be used as the header parameter value in the form of a JSON map of values.
=> teiiddes-2329: 

plugins/org.teiid.designer.transformation.ui/src/org/teiid/designer/transformation/ui/wizards/file/FlatFileRelationalModelFactory.java
Added code to create the headers parameter in the invokeHttp() generation.
=> teiiddes-2329

plugins/org.teiid.designer.relational.ui/src/org/teiid/designer/relational/ui/webservice/WebServiceRelationalModelWizardPage.java
=> TEIIDDES-2694: Generate Web Service Translator Procedures - description of procedures needs update

site/pom.xml
=> tweak site pom

plugins/org.teiid.designer.datatools.ui/src/org/teiid/designer/datatools/profiles/ws/HeaderPropertiesPanel.java, plugins/org.teiid.designer.modelgenerator.wsdl.ui/src/org/teiid/designer/modelgenerator/wsdl/ui/wizards/soap/ImportWsdlSchemaHandler.java, plugins/org.teiid.designer.modelgenerator.wsdl.ui/src/org/teiid/designer/modelgenerator/wsdl/ui/wizards/soap/SchemaTreeModel.java
Added logic to account for null schema type and simple types in WSDL parts.
=> teiiddes-2748

plugins/org.teiid.datatools.connectivity.ui.flatfile/src/org/teiid/designer/datatools/ui/flatfile/Messages.java, plugins/org.teiid.datatools.connectivity.ui.flatfile/src/org/teiid/designer/datatools/ui/flatfile/ReplacementFolderSelectionPageHelper.java, plugins/org.teiid.datatools.connectivity.ui.flatfile/src/org/teiid/designer/datatools/ui/flatfile/messages.properties
- When creating flat file Connection Profile, the file paths are now checked for spaces.
=> TEIIDDES-2493 Checks for file path spaces in flat file CP

plugins/org.teiid.designer.ddl.importer/src/org/teiid/designer/ddl/importer/node/TeiidDdlImporter.java, plugins/org.teiid.designer.ui/plugin.xml, plugins/org.teiid.designer.ui/src/org/teiid/designer/ui/i18n.properties, plugins/org.teiid.designer.ui/src/org/teiid/designer/ui/properties/FloatAsIntPropertyEditorFactory.java, plugins/org.teiid.designer.ui/src/org/teiid/designer/ui/properties/ModelObjectPropertyDescriptor.java, tests/org.teiid.designer.ddl.importer.test/META-INF/MANIFEST.MF, tests/org.teiid.designer.ddl.importer.test/src/org/teiid/designer/ddl/importer/DdlImporterTest.java, tests/org.teiid.designer.ddl.importer.test/testdata/fixed-postgres-vdb.xml
- if cardinality > Integer.MAX_VALUE it is converted to a negative integer the way Teiid expects
- modified property editor to display and edit the large values
- wrote test that imports the dynamic VDB that was failing
Sorry for all the whitespace differences. These noccur when my Eclipse save actions are run. I will change that setting.
=> TEIIDDES-2558 Unable to import attached DDL, invalid cardinality

plugins/org.teiid.designer.teiidimporter.ui/src/org/teiid/designer/teiidimporter/ui/panels/TranslatorHelper.java
Added/Modified HANA driver name and JDBC URL template.
=> teiiddes-2388

plugins/org.teiid.designer.dqp.ui/src/org/teiid/designer/runtime/ui/actions/GenerateRestWarAction.java
Reset rest model map before adding new models for selected VDB.
=> teiiddes-2709

plugins/org.teiid.designer.dqp.ui/src/org/teiid/designer/runtime/ui/i18n.properties, plugins/org.teiid.designer.dqp.ui/src/org/teiid/designer/runtime/ui/wizards/vdbs/GenerateDynamicVdbManager.java, plugins/org.teiid.designer.vdb/src/org/teiid/designer/vdb/XmiVdb.java, plugins/org.teiid.designer.vdb/src/org/teiid/designer/vdb/i18n.properties
* XmiVdb
* If vdb contains udf jars then add a 'lib' property with a warning
that the library needs to be deployed as well
=> TEIIDDES-2713: Adds udf library properties and warnings accordingly

plugins/org.teiid.designer.vdb/src/org/teiid/designer/vdb/VdbUtil.java
* VdbUtil
* Test the iterator has an element before trying to fetch it
=> TEIIDDES-2803: NoSuchElementException when vdb is not in the workspace

plugins/org.teiid.designer.datatools.ui/src/org/teiid/designer/datatools/profiles/ws/ODataProfileDetailsWizardPage.java, plugins/org.teiid.designer.datatools.ui/src/org/teiid/designer/datatools/profiles/ws/PropertyPage.java, plugins/org.teiid.designer.datatools.ui/src/org/teiid/designer/datatools/profiles/ws/WSProfileDetailsWizardPage.java, plugins/org.teiid.designer.datatools.ui/src/org/teiid/designer/datatools/profiles/ws/WSSoapPropertyPage.java, plugins/org.teiid.designer.modelgenerator.wsdl/src/org/teiid/designer/modelgenerator/wsdl/WSSoapConnectionInfoProvider.java, plugins/org.teiid.designer.transformation.ui/META-INF/MANIFEST.MF, plugins/org.teiid.designer.transformation.ui/src/org/teiid/designer/transformation/ui/wizards/rest/TeiidRestImportSourcePage.java, plugins/org.teiid.designer.ui.common/src/org/teiid/designer/ui/common/ICredentialsCommon.java, plugins/org.teiid.designer.ui.common/src/org/teiid/designer/ui/common/widget/CredentialsComposite.java, plugins/org.teiid.designer.ui/src/org/teiid/designer/ui/wizards/wsdl/WsdlUrlDialog.java, plugins/org.teiid.designer.webservice.lib/pom.xml
Added HTTPDigest support for imported REST services.
=> teiiddes-2571

plugins/org.teiid.designer.datatools.ui/META-INF/MANIFEST.MF, plugins/org.teiid.designer.datatools.ui/src/org/teiid/designer/datatools/profiles/ws/WSProfileDetailsWizardPage.java, plugins/org.teiid.designer.datatools.ui/src/org/teiid/designer/datatools/profiles/ws/WSWizardUtils.java
Added logic for testing REST HTTPDigest secured services in the CP editor.
=> teiiddes-2822

plugins/org.teiid.designer.core/META-INF/MANIFEST.MF, plugins/org.teiid.designer.core/src/org/teiid/designer/core/util/URLHelper.java, plugins/org.teiid.designer.datatools.ui/src/org/teiid/designer/datatools/profiles/ws/WSSoapProfileDetailsWizardPage.java, plugins/org.teiid.designer.datatools.ui/src/org/teiid/designer/datatools/profiles/ws/WSWizardUtils.java, plugins/org.teiid.designer.dqp.ui/src/org/teiid/designer/runtime/ui/connection/JndiNameInModelHelper.java, plugins/org.teiid.designer.modelgenerator.wsdl/META-INF/MANIFEST.MF, plugins/org.teiid.designer.modelgenerator.wsdl/src/org/teiid/designer/modelgenerator/wsdl/WSDLReader.java, plugins/org.teiid.designer.modelgenerator.wsdl/src/org/teiid/designer/modelgenerator/wsdl/model/impl/ModelBuilder.java, plugins/org.teiid.designer.modelgenerator.wsdl/src/org/teiid/designer/modelgenerator/wsdl/util/ExtendedWSDLReader.java, plugins/org.teiid.designer.modelgenerator.wsdl/src/org/teiid/designer/modelgenerator/wsdl/util/WSDLSchemaExtractor.java, plugins/org.teiid.designer.ui.common/src/org/teiid/designer/ui/common/widget/CredentialsComposite.java, plugins/org.teiid.designer.ui/src/org/teiid/designer/ui/wizards/wsdl/WsdlUrlDialog.java, plugins/org.teiid.designer.webservice.ui/src/org/teiid/designer/webservice/ui/wizard/WsdlSelectionPage.java
Added HTTP Digest support for SOAP WS imports.
=> teiiddes-2819 

plugins/teiid/org.teiid.runtime.client/src/org/teiid/runtime/client/proc/ProcedureService.java
Removed extraneous SQL from generated transformation.
=> teiiddes-2725

plugins/org.teiid.designer.datatools.ui/src/org/teiid/designer/datatools/ui/i18n.properties
* get back properties which are still used in the code
=> TEIIDDES-3011

features/org.teiid.designer.library.feature/feature.xml, features/pom.xml
Remove unnecesary dependency on org.apache.directory.studio.slf4j.eclipselog
=> Remove unnecesary dependency on org.apache.directory.studio.slf4j.eclipselog

plugins/org.teiid.designer.dqp/src/org/teiid/designer/runtime/i18n.properties
Merging this quick typo fix back into the upstream project.
=> Updated i18n file with typo fixes

plugins/org.teiid.designer.transformation.ui/src/org/teiid/designer/transformation/ui/i18n.properties, plugins/org.teiid.designer.ui/src/org/teiid/designer/ui/i18n.properties
I have only uncommented message in first fix this issue (https://github.com/Teiid-Designer/teiid-designer/commit/3777c0ba279ece026d1a2887088235bc707ab88d) but the message needs to be moved to another properties file.
=> TEIIDDES-3134 - change property file

plugins/org.teiid.designer.datatools.ui/src/org/teiid/designer/datatools/ui/i18n.properties, plugins/org.teiid.designer.dqp.ui/src/org/teiid/designer/runtime/ui/connection/SetConnectionProfileAction.java, plugins/org.teiid.designer.dqp.ui/src/org/teiid/designer/runtime/ui/i18n.properties
moved noProfileProvider properties to another properties file
=> TEIIDDES-3140 - move noProfileProvider properties

plugins/org.teiid.designer.webservice.lib/rest_war_resources/webapps/WEB-INF/classes/org/teiid/rest/services/TeiidRSProviderPost.java
The server check was for XMLType charset, which was not being set.
=> teiiddes-3130: Fix for null charset with large results.

plugins/org.teiid.designer.vdb/src/org/teiid/designer/vdb/XmiVdb.java
Condition was fixed (null never occur)
=> TEIIDDES-3144 - warning dialog shows every time
